### ISSUE TITLE
Getting Error when views are not published

### ISSUE THREAD

**Issue by devadattas** [happytodev/filament-tailwind-color-picker#3]
I get the following error if I don't run the optional view publication command i.e. `php artisan vendor:publish --tag="filament-tailwind-color-picker-views"`

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/56180/201961406-d904ed0a-106e-4ba3-9fb0-ef3dfac8c5c8.png">

```
View [vendor.filament-tailwind-color-picker.forms.components.tailwind-color-picker] not found.
```

**Comment by devadattas** [comment]
@happytodev Please accept the PR https://github.com/happytodev/filament-tailwind-color-picker/pull/4 to fix this issue.

**Comment by happytodev** [comment]
I will check. Thank you for the report.

**Comment by happytodev** [comment]
I confirm this is a bug. Thank you.
